[r=andreserl][bug=][author=smoser] update packaging to pass --ip to maas configure_master_dhcp
This makes a change to use debconf to get the (now required) ip address of the dhcp server, via the debconf name 'maas-dhcp/maas-dhcp-addr'. If left blank, it will
pick the ip address of the named interface from the provided maas-dhcp-interface.

There are some other changes lumped in here also.
 * fix a lintian warning in maas-dhcp.postrm
 * move tests/maas-integration.py to a patch in debian/patches/
   Debian packages are not supposed to modify the trunk directly, and
   'debuild -S' complained about changes to that file that were not accounted for.

diff --git a/debian/maas-dhcp.postinst b/debian/maas-dhcp.postinst
--- a/debian/maas-dhcp.postinst
+++ b/debian/maas-dhcp.postinst
@@ -28,9 +28,20 @@ if ([ "$1" = "configure" ] && [ -z "$2" ]) || [ "$1" = "reconfigure" ] || [ -n "
 		db_get maas-dhcp/maas-dhcp-interface || true
 		interface="$RET"
 
+		# Obtain the interfaces
+		db_get maas-dhcp/maas-dhcp-addr || true
+		addr="$RET"
+
+		if [ -z "$addr" ]; then
+			addr=$(ifconfig "$interface" |
+			       awk '$1 == "inet" { sub("addr:","",$2); print $2 }')
+			[ -n "$addr" ] ||
+				{ echo "failed to get ip for $interface" 1>&2; exit 1; }
+		fi
+
 		maas config_master_dhcp --ip-range-low="$range_low" --ip-range-high="$range_high" \
 				--router-ip="$gateway" --subnet-mask="$netmask" --broadcast-ip="$broadcast" \
-				--interface="$interface"
+				--interface="$interface" --ip="$addr"
 	fi
 
 fi
